version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_USER: ekow
      POSTGRES_PASSWORD: Eai1185781455
      POSTGRES_DB: notifications_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
