GET http://localhost:3000
Authorization: Bearer toKen

### register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "ekow.a.indome@gmail.com",
    "password": "password@school"
}

### login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ekow.a.indome@gmail.com",
    "password": "password@school"
}

### refresh-token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "refresh-token"
}

### logout route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "refresh-token"
}
